package exceptionhandling;

class Test12 {

	public static void main(String[] args) {
		try {
			System.out.println("Hello");
			}
		catch(ArithmeticException e) {
			
		}

	}

}
