package exceptionhandling;

 class Test5 {

	public static void main(String[] args) {
	try {
		System.out.println("Hello");
	}
	catch(Error e) {}//take interruptedException then throw exception
	}
	}
	


